services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      # Optional: Enable encrypted settings storage
      - ENCRYPTION=${PB_ENCRYPTION_KEY} 
    volumes:
      - ./pb_data:/pb_data
      - ./pb_public:/pb_public  # optional
      - ./pb_hooks:/pb_hooks    # optional