---
# Supabase Docker Compose file for Easement
# Reference: https://supabase.com/docs/guides/self-hosting/docker
# For production, update all secrets and credentials in your .env file

services:
  db:
    image: supabase/postgres:15.1.0.89
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your-super-secret-and-long-postgres-password}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - supabase-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  kong:
    image: supabase/kong:latest
    restart: always
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - supabase-kong-config:/var/lib/kong

  studio:
    image: supabase/studio:latest
    restart: always
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      SUPABASE_PUBLIC_URL: ${SUPABASE_PUBLIC_URL:-http://localhost:8000}
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME:-supabase}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD:-this_password_is_insecure_and_should_be_updated}
    ports:
      - "8080:3000"

  rest:
    image: postgrest/postgrest:latest
    restart: always
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-your-super-secret-and-long-postgres-password}@db:5432/${POSTGRES_DB:-postgres}
      PGRST_JWT_SECRET: ${JWT_SECRET:-HSXVHIe4M2C9VyceZJFQK75NNQ7xM351WKo9YcPC}
      PGRST_DB_ANON_ROLE: ${DB_ANON_ROLE:-anon}
    depends_on:
      - db
    ports:
      - "3000:3000"

  auth:
    image: supabase/gotrue:latest
    restart: always
    environment:
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-your-super-secret-and-long-postgres-password}@db:5432/${POSTGRES_DB:-postgres}
      GOTRUE_JWT_SECRET: ${JWT_SECRET:-HSXVHIe4M2C9VyceZJFQK75NNQ7xM351WKo9YcPC}
      GOTRUE_SITE_URL: ${SITE_URL:-http://localhost:8000}
      GOTRUE_SMTP_HOST: ${SMTP_HOST:-smtp.example.com}
      GOTRUE_SMTP_PORT: ${SMTP_PORT:-587}
      GOTRUE_SMTP_USER: ${SMTP_USER:-user}
      GOTRUE_SMTP_PASS: ${SMTP_PASS:-pass}
      GOTRUE_SMTP_ADMIN_EMAIL: ${SMTP_ADMIN_EMAIL:-admin@example.com}
    depends_on:
      - db
    ports:
      - "9999:9999"

  realtime:
    image: supabase/realtime:latest
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-your-super-secret-and-long-postgres-password}
      DB_NAME: ${POSTGRES_DB:-postgres}
      PORT: 4000
    depends_on:
      - db
    ports:
      - "4000:4000"

  storage:
    image: supabase/storage-api:latest
    restart: always
    environment:
      POSTGRES_CONNECTION_STRING: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-your-super-secret-and-long-postgres-password}@db:5432/${POSTGRES_DB:-postgres}
      ANON_KEY: ${ANON_KEY:-your-anon-key}
      SERVICE_KEY: ${SERVICE_ROLE_KEY:-your-service-role-key}
      STORAGE_BACKEND: file
      FILE_SIZE_LIMIT: 52428800
      STORAGE_S3_BUCKET: ${GLOBAL_S3_BUCKET:-}
      STORAGE_S3_REGION: ${REGION:-}
      STORAGE_S3_ACCESS_KEY: ${S3_ACCESS_KEY:-}
      STORAGE_S3_SECRET_KEY: ${S3_SECRET_KEY:-}
    depends_on:
      - db
    ports:
      - "5000:5000"

  meta:
    image: supabase/postgres-meta:latest
    restart: always
    environment:
      PG_META_DB_HOST: db
      PG_META_DB_PORT: 5432
      PG_META_DB_USER: ${POSTGRES_USER:-postgres}
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD:-your-super-secret-and-long-postgres-password}
      PG_META_DB_NAME: ${POSTGRES_DB:-postgres}

    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  supabase-db-data:
  supabase-kong-config:
